export const ECUADOR_PROVINCES = [
  "Azuay",
  "Bolívar",
  "Cañar",
  "Carchi",
  "Chimborazo",
  "Cotopaxi",
  "El Oro",
  "Esmeraldas",
  "Galápagos",
  "Guayas",
  "Imbabura",
  "Loja",
  "Los Ríos",
  "Manabí",
  "Morona Santiago",
  "Napo",
  "Orellana",
  "Pastaza",
  "Pichincha",
  "Santa Elena",
  "Santo Domingo de los Tsáchilas",
  "Sucumbíos",
  "Tungurahua",
  "Zamora Chinchipe",
];

export const CANTON_SUGGESTIONS = [
  "Manta",
  "Montecristi",
  "Portoviejo",
  "Chone",
  "Jipijapa",
  "Jaramijó",
  "Santa Ana",
  "El Carmen",
  "Bahía de Caráquez",
  "Pedernales",
  "Guayaquil",
  "Durán",
  "Samborondón",
  "Quevedo",
  "Salinas",
  "La Libertad",
  "Santa Elena",
  "Cuenca",
  "Gualaceo",
  "Azogues",
  "Riobamba",
  "Ambato",
  "Latacunga",
  "Santo Domingo",
  "Ibarra",
  "Otavalo",
  "Loja",
  "Machala",
  "Esmeraldas",
  "Nueva Loja",
  "Tena",
  "Puyo",
  "Coca",
  "Zamora",
  "Macas",
  "Puerto Ayora",
];

export const PARISH_SUGGESTIONS = [
  "Centro",
  "Urbana",
  "Rural",
  "Norte",
  "Sur",
  "Este",
  "Oeste",
  "Tarqui",
  "Eloy Alfaro",
  "Sucre",
  "San Sebastián",
  "San Blas",
  "Carcelén",
  "Calderón",
  "Abdón Calderón",
  "Letamendi",
  "Ximena",
  "Pascuales",
  "Balao",
  "Nueva Loja",
  "El Valle",
  "Tumbaco",
  "Pomasqui",
  "Cotocollao",
];
